# Keybinds
keybind super return run kitty
keybind super q kill_active
keybind super n next_toplevel
keybind super g toggle_floating
keybind super+shift q exit

# Pointer
keybind super pointer_left_click move
keybind super pointer_right_click resize

# View tags
keybind super 1 view_tag
keybind super 2 view_tag
keybind super 3 view_tag
keybind super 4 view_tag
keybind super 5 view_tag
keybind super 6 view_tag
keybind super 7 view_tag
keybind super 8 view_tag
keybind super 9 view_tag

# Move focused window to tag
keybind super+shift 1 move_focused_to_tag
keybind super+shift 2 move_focused_to_tag
keybind super+shift 3 move_focused_to_tag
keybind super+shift 4 move_focused_to_tag
keybind super+shift 5 move_focused_to_tag
keybind super+shift 6 move_focused_to_tag
keybind super+shift 7 move_focused_to_tag
keybind super+shift 8 move_focused_to_tag
keybind super+shift 9 move_focused_to_tag

# Border
border_width 3
border_color_active #e6992eff
border_color_inactive #4d4d4dff
